name: healTalkpatient
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  convex_bottom_bar: ^3.0.0
  lite_rolling_switch: ^0.1.1
  fluttertoast: ^8.0.7
  
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1 
  firebase_auth: ^1.3.0 
  firebase_database: ^7.1.0
  
  shared_preferences: ^2.0.6

  gender_picker: ^1.1.0
  get: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
 
  
  assets:
    - asset/img/
    - asset/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Lato
    fonts:
    - asset: asset/font/Lato-Regular.ttf
      
          # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
